name: Python CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building..."
      - run: sleep 15

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: echo "Testing..."