name: Python CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Build Message
        run: echo "Building Application..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Test Message
        run: echo "Running Tests..."